filegroup(
    name = "all",
    srcs = [
        "//cc_toolchain/wrappers/mac:all",
        "//cc_toolchain/wrappers/posix:all",
        "//cc_toolchain/wrappers/windows:all",
    ],
    visibility = ["//visibility:public"],
)
