filegroup(
    name = "all",
    srcs = [
        "//cc_toolchain/wrappers/darwin:all",
        "//cc_toolchain/wrappers/linux:all",
        "//cc_toolchain/wrappers/windows:all",
    ],
    visibility = ["//visibility:public"],
)
